name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '21'
          java-package: jdk

      - uses: azure/setup-kubectl@v4
        id: install

      - name: Run tests
        continue-on-error: true
        run:  mvn clean verify -Pintegration-test

      - name: Log
        run: |
          export KUBECONFIG=$(pwd)/target/k3s.yaml
          kubectl logs -l app/name=tir